### ISSUE TITLE
iPhone 6 & 6+ layout issue

### ISSUE THREAD

**Issue by AFcgi** [86/TRZSlideLicenseViewController#12]
I have a layout issue with iPhone 6 and 6+. Your ScrollView-Content isn't correct for the first license view. Also the scrollView delegates doesn't operate correctly.

**Comment by 86** [comment]
Can I have a screenshot shown this issue?

**Comment by AFcgi** [comment]
Here is the screenshot.
![simulator screen shot 04 03 2016 10 42 14](https://cloud.githubusercontent.com/assets/13546232/13523450/d428af26-e1f5-11e5-9a20-e10a1417a44b.png)

**Comment by 86** [comment]
Thanks :+1:
I'll try to resolve this issue

**Comment by 86** [comment]
This issue is resolved. Try version 0.9.6.
